version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: AlphaMySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@admin123
      MYSQL_DATABASE: Alpha
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - alpha-games
  main:
    container_name: AlphaServer
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: Alpha
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - alpha-games
networks:
  alpha-games:
    driver: bridge